"""add request logs table

Revision ID: 3b487c156026
Revises: 83947c419cc2
Create Date: 2026-07-06 17:06:26.590521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b487c156026'
down_revision: Union[str, Sequence[str], None] = '83947c419cc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('plan_name', sa.String(length=50), nullable=True),
    sa.Column('route_path', sa.String(length=255), nullable=False),
    sa.Column('http_method', sa.String(length=10), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('remaining_tokens', sa.Integer(), nullable=True),
    sa.Column('retry_after_seconds', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_request_logs_api_key_created_at', 'request_logs', ['api_key_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_request_logs_api_key_id'), 'request_logs', ['api_key_id'], unique=False)
    op.create_index('ix_request_logs_decision_created_at', 'request_logs', ['decision', 'created_at'], unique=False)
    op.create_index(op.f('ix_request_logs_request_id'), 'request_logs', ['request_id'], unique=True)
    op.create_index('ix_request_logs_route_created_at', 'request_logs', ['route_path', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_request_logs_route_created_at', table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_request_id'), table_name='request_logs')
    op.drop_index('ix_request_logs_decision_created_at', table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_api_key_id'), table_name='request_logs')
    op.drop_index('ix_request_logs_api_key_created_at', table_name='request_logs')
    op.drop_table('request_logs')
    # ### end Alembic commands ###
