"""add refill amount and unit to policies

Revision ID: 6ba1385f27ba
Revises: 8a538cc4b4e3
Create Date: 2026-07-06 22:13:15.950053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ba1385f27ba'
down_revision: Union[str, Sequence[str], None] = '8a538cc4b4e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rate_limit_policies', sa.Column('refill_amount', sa.Float(), server_default='1', nullable=False))
    op.add_column('rate_limit_policies', sa.Column('refill_unit', sa.String(length=20), server_default='second', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rate_limit_policies', 'refill_unit')
    op.drop_column('rate_limit_policies', 'refill_amount')
    # ### end Alembic commands ###
