"""add project policy and subject fields to request logs

Revision ID: 70212ffa4f54
Revises: 6ba1385f27ba
Create Date: 2026-07-06 23:37:39.172748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70212ffa4f54'
down_revision: Union[str, Sequence[str], None] = '6ba1385f27ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_logs', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('request_logs', sa.Column('policy_id', sa.Integer(), nullable=True))
    op.add_column('request_logs', sa.Column('subject_hash', sa.String(length=64), nullable=True))
    op.drop_index(op.f('ix_request_logs_api_key_created_at'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_decision_created_at'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_route_created_at'), table_name='request_logs')
    op.create_index('ix_request_logs_api_key_created', 'request_logs', ['api_key_id', 'created_at'], unique=False)
    op.create_index('ix_request_logs_decision_created', 'request_logs', ['decision', 'created_at'], unique=False)
    op.create_index(op.f('ix_request_logs_policy_id'), 'request_logs', ['policy_id'], unique=False)
    op.create_index(op.f('ix_request_logs_project_id'), 'request_logs', ['project_id'], unique=False)
    op.create_index('ix_request_logs_project_policy_created', 'request_logs', ['project_id', 'policy_id', 'created_at'], unique=False)
    op.create_index('ix_request_logs_route_created', 'request_logs', ['route_path', 'created_at'], unique=False)
    op.create_foreign_key(None, 'request_logs', 'rate_limit_policies', ['policy_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'request_logs', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request_logs', type_='foreignkey')
    op.drop_constraint(None, 'request_logs', type_='foreignkey')
    op.drop_index('ix_request_logs_route_created', table_name='request_logs')
    op.drop_index('ix_request_logs_project_policy_created', table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_project_id'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_policy_id'), table_name='request_logs')
    op.drop_index('ix_request_logs_decision_created', table_name='request_logs')
    op.drop_index('ix_request_logs_api_key_created', table_name='request_logs')
    op.create_index(op.f('ix_request_logs_route_created_at'), 'request_logs', ['route_path', 'created_at'], unique=False)
    op.create_index(op.f('ix_request_logs_decision_created_at'), 'request_logs', ['decision', 'created_at'], unique=False)
    op.create_index(op.f('ix_request_logs_api_key_created_at'), 'request_logs', ['api_key_id', 'created_at'], unique=False)
    op.drop_column('request_logs', 'subject_hash')
    op.drop_column('request_logs', 'policy_id')
    op.drop_column('request_logs', 'project_id')
    # ### end Alembic commands ###
