"""create plans api keys and rate limit policies

Revision ID: 83947c419cc2
Revises: 3a389ed74c23
Create Date: 2026-07-06 14:26:06.801022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83947c419cc2'
down_revision: Union[str, Sequence[str], None] = '3a389ed74c23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_api_keys_plan_id'), 'api_keys', ['plan_id'], unique=False)
    op.create_table('rate_limit_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('route_path', sa.String(length=255), nullable=False),
    sa.Column('http_method', sa.String(length=10), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('refill_rate', sa.Float(), nullable=False),
    sa.Column('tokens_required', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity > 0', name='ck_policy_capacity_positive'),
    sa.CheckConstraint('refill_rate > 0', name='ck_policy_refill_rate_positive'),
    sa.CheckConstraint('tokens_required > 0', name='ck_policy_tokens_required_positive'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'route_path', 'http_method', name='uq_policy_plan_route_method')
    )
    op.create_index(op.f('ix_rate_limit_policies_plan_id'), 'rate_limit_policies', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_limit_policies_plan_id'), table_name='rate_limit_policies')
    op.drop_table('rate_limit_policies')
    op.drop_index(op.f('ix_api_keys_plan_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('plans')
    # ### end Alembic commands ###
