"""add projects and project scoped policies

Revision ID: 8a538cc4b4e3
Revises: 3b487c156026
Create Date: 2026-07-06 20:37:24.261150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a538cc4b4e3'
down_revision: Union[str, Sequence[str], None] = '3b487c156026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.add_column('api_keys', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_api_keys_project_id'), 'api_keys', ['project_id'], unique=False)
    op.create_foreign_key(None, 'api_keys', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('rate_limit_policies', sa.Column('project_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('uq_policy_plan_route_method'), 'rate_limit_policies', type_='unique')
    op.create_index(op.f('ix_rate_limit_policies_project_id'), 'rate_limit_policies', ['project_id'], unique=False)
    op.create_unique_constraint('uq_policy_project_plan_route_method', 'rate_limit_policies', ['project_id', 'plan_id', 'route_path', 'http_method'])
    op.create_foreign_key(None, 'rate_limit_policies', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rate_limit_policies', type_='foreignkey')
    op.drop_constraint('uq_policy_project_plan_route_method', 'rate_limit_policies', type_='unique')
    op.drop_index(op.f('ix_rate_limit_policies_project_id'), table_name='rate_limit_policies')
    op.create_unique_constraint(op.f('uq_policy_plan_route_method'), 'rate_limit_policies', ['plan_id', 'route_path', 'http_method'], postgresql_nulls_not_distinct=False)
    op.drop_column('rate_limit_policies', 'project_id')
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_index(op.f('ix_api_keys_project_id'), table_name='api_keys')
    op.drop_column('api_keys', 'project_id')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
